stages:
  preprocess:
    cmd: python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - data/raw
    params:
      - preprocess.image_size
      - preprocess.train_split
      - preprocess.val_split
      - preprocess.test_split
      - preprocess.seed
    outs:
      - data/processed

  train:
    cmd: python -m src.models.train
    deps:
      - src/models/train.py
      - src/models/model.py
      - data/processed
    params:
      - train.epochs
      - train.batch_size
      - train.learning_rate
    outs:
      - models/cats_dogs_cnn_weights.pkl
    metrics:
      - reports/metrics.json:
          cache: false
