apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-dogs-api
  labels:
    app: cats-dogs-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cats-dogs-api
  template:
    metadata:
      labels:
        app: cats-dogs-api
    spec:
      containers:
        - name: cats-dogs-api
          image: docker.io/YOUR_DOCKERHUB_USERNAME/cats-dogs-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: /app/models/cats_dogs_cnn.weights.h5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
